"""adiciona_campo_erros

Revision ID: 1c87b8e240dc
Revises: ba5027158580
Create Date: 2025-07-14 12:18:47.815074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c87b8e240dc'
down_revision: Union[str, Sequence[str], None] = 'ba5027158580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solucoes', sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solucoes', 'errors')
    # ### end Alembic commands ###
