"""alter_solucao

Revision ID: 7857ecc66ab5
Revises: 98df7c62658b
Create Date: 2025-07-14 11:58:04.108105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7857ecc66ab5'
down_revision: Union[str, Sequence[str], None] = '98df7c62658b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solucoes', sa.Column('solver_status', sa.String(), nullable=False))
    op.add_column('solucoes', sa.Column('time_to_solve', sa.Interval(), nullable=False))
    op.add_column('solucoes', sa.Column('solver_type', sa.String(), nullable=False))
    op.drop_column('solucoes', 'solver_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solucoes', sa.Column('solver_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('solucoes', 'solver_type')
    op.drop_column('solucoes', 'time_to_solve')
    op.drop_column('solucoes', 'solver_status')
    # ### end Alembic commands ###
