"""alter_solucao

Revision ID: ba5027158580
Revises: 7857ecc66ab5
Create Date: 2025-07-14 11:59:22.749048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5027158580'
down_revision: Union[str, Sequence[str], None] = '7857ecc66ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solucoes', sa.Column('solver_runing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solucoes', 'solver_runing')
    # ### end Alembic commands ###
