
    create table institutions (
        active boolean not null,
        id bigint generated by default as identity,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table solutions (
        created_at timestamp(6) with time zone,
        duration_millis bigint,
        id bigint generated by default as identity,
        institution_id bigint not null,
        error_message varchar(255),
        input_path varchar(255),
        model_name varchar(255),
        output_path varchar(255),
        solver_status varchar(255) check (solver_status in ('OPTIMAL','FEASIBLE','INFEASIBLE','ERROR','RUNNING','TIMEOUT','PENDING','UNKNOWN')),
        warning_message varchar(255),
        primary key (id)
    );

    create table users (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')),
        primary key (id)
    );

    alter table if exists solutions 
       add constraint FKbimdo6kcdtoefepw5hjxf6k0q 
       foreign key (institution_id) 
       references institutions;

    create table institutions (
        active boolean not null,
        id bigint generated by default as identity,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table solutions (
        created_at timestamp(6) with time zone,
        duration_millis bigint,
        id bigint generated by default as identity,
        institution_id bigint not null,
        error_message varchar(255),
        input_path varchar(255),
        model_name varchar(255),
        output_path varchar(255),
        solver_status varchar(255) check (solver_status in ('OPTIMAL','FEASIBLE','INFEASIBLE','ERROR','RUNNING','TIMEOUT','PENDING','UNKNOWN')),
        warning_message varchar(255),
        primary key (id)
    );

    create table users (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')),
        primary key (id)
    );

    alter table if exists solutions 
       add constraint FKbimdo6kcdtoefepw5hjxf6k0q 
       foreign key (institution_id) 
       references institutions;

    create table institutions (
        active boolean not null,
        id bigint generated by default as identity,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table solutions (
        created_at timestamp(6) with time zone,
        duration_millis bigint,
        id bigint generated by default as identity,
        institution_id bigint not null,
        error_message varchar(255),
        input_path varchar(255),
        model_name varchar(255),
        output_path varchar(255),
        solver_status varchar(255) check (solver_status in ('OPTIMAL','FEASIBLE','INFEASIBLE','ERROR','RUNNING','TIMEOUT','PENDING','UNKNOWN')),
        warning_message varchar(255),
        primary key (id)
    );

    create table users (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')),
        primary key (id)
    );

    alter table if exists solutions 
       add constraint FKbimdo6kcdtoefepw5hjxf6k0q 
       foreign key (institution_id) 
       references institutions;

    create table institutions (
        active boolean not null,
        id bigint generated by default as identity,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table solutions (
        created_at timestamp(6) with time zone,
        duration_millis bigint,
        id bigint generated by default as identity,
        institution_id bigint not null,
        error_message varchar(255),
        input_path varchar(255),
        model_name varchar(255),
        output_path varchar(255),
        solver_status varchar(255) check (solver_status in ('OPTIMAL','FEASIBLE','INFEASIBLE','ERROR','RUNNING','TIMEOUT','PENDING','UNKNOWN')),
        warning_message varchar(255),
        primary key (id)
    );

    create table users (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')),
        primary key (id)
    );

    alter table if exists solutions 
       add constraint FKbimdo6kcdtoefepw5hjxf6k0q 
       foreign key (institution_id) 
       references institutions;

    create table institutions (
        active boolean not null,
        id bigint generated by default as identity,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table solutions (
        created_at timestamp(6) with time zone,
        duration_millis bigint,
        id bigint generated by default as identity,
        institution_id bigint not null,
        error_message varchar(255),
        input_path varchar(255),
        model_name varchar(255),
        output_path varchar(255),
        solver_status varchar(255) check (solver_status in ('OPTIMAL','FEASIBLE','INFEASIBLE','ERROR','RUNNING','TIMEOUT','PENDING','UNKNOWN')),
        warning_message varchar(255),
        primary key (id)
    );

    create table users (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')),
        primary key (id)
    );

    alter table if exists solutions 
       add constraint FKbimdo6kcdtoefepw5hjxf6k0q 
       foreign key (institution_id) 
       references institutions;

    create table institutions (
        active boolean not null,
        id bigint generated by default as identity,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table solutions (
        created_at timestamp(6) with time zone,
        duration_millis bigint,
        id bigint generated by default as identity,
        institution_id bigint not null,
        error_message varchar(255),
        input_path varchar(255),
        model_name varchar(255),
        output_path varchar(255),
        solver_status varchar(255) check (solver_status in ('OPTIMAL','FEASIBLE','INFEASIBLE','ERROR','RUNNING','TIMEOUT','PENDING','UNKNOWN')),
        warning_message varchar(255),
        primary key (id)
    );

    create table users (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')),
        primary key (id)
    );

    alter table if exists solutions 
       add constraint FKbimdo6kcdtoefepw5hjxf6k0q 
       foreign key (institution_id) 
       references institutions;

    create table institutions (
        active boolean not null,
        id bigint generated by default as identity,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table solutions (
        created_at timestamp(6) with time zone,
        duration_millis bigint,
        id bigint generated by default as identity,
        institution_id bigint not null,
        error_message varchar(255),
        input_path varchar(255),
        model_name varchar(255),
        output_path varchar(255),
        solver_status varchar(255) check (solver_status in ('OPTIMAL','FEASIBLE','INFEASIBLE','ERROR','RUNNING','TIMEOUT','PENDING','UNKNOWN')),
        warning_message varchar(255),
        primary key (id)
    );

    create table users (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')),
        primary key (id)
    );

    alter table if exists solutions 
       add constraint FKbimdo6kcdtoefepw5hjxf6k0q 
       foreign key (institution_id) 
       references institutions;
