
    create table institutions (
        active boolean not null,
        id bigint generated by default as identity,
        code varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table solutions (
        created_at timestamp(6) with time zone,
        duration_millis bigint,
        id bigint generated by default as identity,
        institution_id bigint not null,
        user_id bigint not null,
        classroom_output_path varchar(1024),
        input_path varchar(1024),
        output_path varchar(1024),
        teacher_output_path varchar(1024),
        error_message TEXT,
        model_name varchar(255),
        solver_status varchar(255) check (solver_status in ('OPTIMAL','FEASIBLE','INFEASIBLE','ERROR','RUNNING','TIMEOUT','PENDING','UNKNOWN')),
        warning_message TEXT,
        primary key (id)
    );

    create table user_institution_roles (
        id bigint generated by default as identity,
        institution_id bigint,
        user_id bigint,
        role varchar(255) check (role in ('MANAGER','TEACHER','OWNER')),
        primary key (id)
    );

    create table users (
        active boolean not null,
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')),
        primary key (id)
    );

    alter table if exists solutions 
       add constraint fk_solutions_institutions 
       foreign key (institution_id) 
       references institutions;

    alter table if exists solutions 
       add constraint fk_solutions_users 
       foreign key (user_id) 
       references users;

    alter table if exists user_institution_roles 
       add constraint fk_uir_institutions 
       foreign key (institution_id) 
       references institutions;

    alter table if exists user_institution_roles 
       add constraint fk_uir_users 
       foreign key (user_id) 
       references users;
